Added facingMode parameter to choose camera type
ysuzuki19/react-qrcode-reader pull request #6
Opened 2023-03-07 19:27 UTC by agustencp

2023-03-08 17:23 UTC, ysuzuki19 requested changes
Hi, @agustencp ,
Thank you for your PR!

I would like to deprecate the `deviceId` prop and integrate it into `videoConstraints`.

2023-03-08 17:23 UTC, ysuzuki19 commented on package/lib/index.tsx
> +  facingMode?: string;
Could you change `videoConstraints`?

And remove line of `deviceId`.

2023-03-08 17:23 UTC, ysuzuki19 commented on package/lib/index.tsx
> +      videoConstraints={{ deviceId, facingMode }}
With the change above,

Please change to input `videoConstraints`.

2023-03-08 17:24 UTC, ysuzuki19 commented
And I would like to update doc(update `README`, add `MIGRATION.md`).

Shall I do it?

2023-03-08 17:57 UTC, agustencp commented on package/lib/index.tsx
> +  facingMode?: string;
ok, I will update it

2023-03-08 18:00 UTC, agustencp commented
> And I would like to update doc(update `README`, add `MIGRATION.md`).
> 
> Shall I do it?

Right, `README` is ignored, that's why it didn't get on this PR

2023-03-09 02:22 UTC, ysuzuki19 commented
Thank you the change
I'll see the code tonight (from Tokyo)

2023-03-09 15:13 UTC, ysuzuki19 commented
Oh sorry, i didn't explain enough.

This repository has two meaning of `README`, that are "README for GitHub" and "README for npm".

In `lib/package.json`, the script `npm run prepublish` copy some files at root of repository for npm package.

So you can update `README` of npm package by updating `README` at root of repository without updating `.gitignore`.

2023-03-09 16:04 UTC, agustencp commented
> Oh sorry, i didn't explain enough.
> 
> This repository has two meaning of `README`, that are "README for GitHub" and "README for npm".
> 
> In `lib/package.json`, the script `npm run prepublish` copy some files at root of repository for npm package.
> 
> So you can update `README` of npm package by updating `README` at root of repository without updating `.gitignore`.

ok, done

2023-03-09 16:11 UTC, ysuzuki19 commented
okay, the code looks like good!

Can you restore `lib/package-lock.json`?

After that, I'll verify operation on my devices and merge it.

2023-03-09 16:50 UTC, agustencp commented
> okay, the code looks like good!
> 
> Can you restore `lib/package-lock.json`?
> 
> After that, I'll verify operation on my devices and merge it.

Done!

2023-03-10 14:38 UTC, ysuzuki19 approved these changes

2023-03-10 14:42 UTC, ysuzuki19 commented
@agustencp 
Thanks changing.

The code looks good and I verified operation on chrome and ios-safari (Simulator).

2023-03-10 14:42 UTC, ysuzuki19 commented
plan to do, I will merge it and publish new version at this weekend.

2023-03-12 14:14 UTC, merged